# Generated by Django 3.2.11 on 2024-01-03 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_verificationcode_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 11, 46, 10, 278476, tzinfo=utc)),
        ),
    ]
